spring:
  datasource:
    url: "jdbc:mariadb://localhost:15215/mapsy?createDatabaseIfNotExist=true"
    username: "root"
    password: "password"
discord:
  forced-admins:
    - 158120884014546944
    - 113392954206347264
